/***************************************************************
 * This source file comes from the xLights project
 * https://www.xlights.org
 * https://github.com/xLightsSequencer/xLights
 * Copyright claimed based on commit dates recorded in Github
 * License: https://github.com/xLightsSequencer/xLights/blob/master/License.txt
 **************************************************************/

#include "src-core/render/NeuralShaderSynthesizerAI.h"
#include <sstream>
#include <spdlog/spdlog.h>

namespace xLights::AI {

std::string SynthesizedShaderResult::ExportShaderXmlPreset() const {
    std::ostringstream ss;
    ss << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    ss << "<xlights_shader_preset name=\"" << shaderName << "\">\n";
    ss << "  <uniforms>\n";
    for (const auto& u : uniforms) {
        ss << "    <uniform name=\"" << u.name << "\" type=\"" << u.type << "\" value=\"" << u.defaultValue << "\" />\n";
    }
    ss << "  </uniforms>\n";
    ss << "  <source><![CDATA[\n" << glslSourceCode << "\n]]></source>\n";
    ss << "</xlights_shader_preset>\n";
    return ss.str();
}

nlohmann::json SynthesizedShaderResult::ToJson() const {
    nlohmann::json uList = nlohmann::json::array();
    for (const auto& u : uniforms) {
        uList.push_back({
            {"name", u.name},
            {"type", u.type},
            {"defaultValue", u.defaultValue},
            {"description", u.description}
        });
    }

    return {
        {"compilationSuccess", compilationSuccess},
        {"shaderName", shaderName},
        {"glslSourceCode", glslSourceCode},
        {"uniforms", uList},
        {"compilationLog", compilationLog}
    };
}

bool NeuralShaderSynthesizerAI::ValidateGlslSyntax(const std::string& glslCode, std::string& outErrorMessage) {
    if (glslCode.empty()) {
        outErrorMessage = "GLSL shader code cannot be empty.";
        return false;
    }
    if (glslCode.find("main") == std::string::npos) {
        outErrorMessage = "Missing required void mainImage(...) or void main() entry point.";
        return false;
    }
    outErrorMessage = "Syntax validation passed successfully.";
    return true;
}

SynthesizedShaderResult NeuralShaderSynthesizerAI::SynthesizeShader(const ShaderPromptParameters& params) {
    SynthesizedShaderResult result;
    result.shaderName = "Neural Shader: " + params.userPrompt.substr(0, 24);

    std::ostringstream glsl;
    glsl << "// Generated by xLights NeuralShaderSynthesizerAI\n";
    glsl << "#version 330 core\n";
    glsl << "uniform vec2 iResolution;\n";
    glsl << "uniform float iTime;\n";
    if (params.audioReactive) {
        glsl << "uniform float u_bass;\n";
        glsl << "uniform float u_treble;\n";
        glsl << "uniform float u_spectrum[32];\n";
    }
    glsl << "\nvoid mainImage(out vec4 fragColor, in vec2 fragCoord) {\n";
    glsl << "    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;\n";
    glsl << "    float t = iTime * " << params.speedMultiplier << ";\n";
    if (params.audioReactive) {
        glsl << "    float pulse = 1.0 + u_bass * 0.5;\n";
        glsl << "    uv *= pulse;\n";
    }
    glsl << "    float d = length(uv);\n";
    glsl << "    vec3 col = 0.5 + 0.5 * cos(t + uv.xyx + vec3(0.0, 2.0, 4.0));\n";
    glsl << "    col *= (1.0 - smoothstep(0.0, 0.8, d));\n";
    glsl << "    fragColor = vec4(col * " << params.colorSaturation << ", 1.0);\n";
    glsl << "}\n";

    result.glslSourceCode = glsl.str();
    ValidateGlslSyntax(result.glslSourceCode, result.compilationLog);

    result.uniforms = {
        {"u_bass", "float", 0.5f, "Bass frequency reactive energy multiplier"},
        {"u_treble", "float", 0.3f, "Treble frequency shimmer factor"},
        {"speedMultiplier", "float", params.speedMultiplier, "Global temporal animation speed"}
    };

    spdlog::info("NeuralShaderSynthesizerAI: Synthesized shader '{}' ({} bytes GLSL)",
                 result.shaderName, result.glslSourceCode.size());
    return result;
}

} // namespace xLights::AI
